# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

# Import Auth routes
auth:
    resource: routes/auth.yaml

# Import API v1 routes
api_v1:
    resource: routes/api_v1.yaml

# Import API v2 routes  
api_v2:
    resource: routes/api_v2.yaml
